### ISSUE TITLE
Add to Cart and Checkout False Positives

### ISSUE THREAD

**Issue by GenericPerson1** [webhasan/gtm-datalayer-for-shopify#1]
I am seeing a lot of False Positives regarding add to cart and checkout. It deviates about 10x from the Shopify Analytics regarding Add to Cart and Checkout.

Expected behavior :

Only when a user uses Dynamic Buy Button a Add To Cart and Checkout is expected

i.e. Shopify Direct Checkout Tracking ( as add_to_cart & begin_checkout)

Actual Behavior:

A very consistent amount of Add to Cart + Begin Checkout (always at the exact same Timestamp) gradually adds up during the day, deviating about 10x from the Shopify Analytics.

Currently running Prestige Theme, latest version. No custom code on the product pages.

**Comment by webhasan** [comment]
If you see any duplicate event, first make sure you don't have any apps like "Google & YouTube" that could be responsible for those events.

In almost all cases, I have found that when there is a duplicate event, one of the events is coming from the "Google & YouTube" app.

So, before discussing further, can you add an [event prefix](https://youtu.be/98w-kEKLICQ?t=1221) and test it?
