### ISSUE TITLE
Duplicate "Add to Cart" Event and Multiple "Add to Cart" and "Remove from Cart" Events Triggered by Shipping Calculation

### ISSUE THREAD

**Issue by vitorwell** [webhasan/gtm-datalayer-for-shopify#2]
**Description**
I am experiencing two issues in my Shopify store:

- Duplicate "Add to Cart" Event: When the "Add to Cart" button is clicked, the "add to cart" event is triggered twice.
- Multiple "Add to Cart" and "Remove from Cart" Events: When calculating shipping on the product page using the [Smart Shipping Calculation](https://apps.shopify.com/smart-shipping-calculation) plugin, multiple "add to cart" and "remove from cart" events are fired.

**Steps to Reproduce**

- Navigate to a product page.
- Click the "Add to Cart" button.
- Observe the tag assistant requests to see that the "add to cart" event is triggered twice.

To reproduce the second issue:

- Navigate to a product page.
- Use the Smart Shipping Calculation plugin to calculate shipping.
- Observe the network requests or event logs to see multiple "add to cart" and "remove from cart" events being fired.

**Expected Behavior**

- The "Add to Cart" button should trigger the "add to cart" event only once.
- Calculating shipping should not trigger any "add to cart" or "remove from cart" events.

 Actual Behavior
- Clicking the "Add to Cart" button triggers the "add to cart" event twice.
- Calculating shipping triggers multiple "add to cart" and "remove from cart" events.

**Environment**

- Theme: Dawn
- Theme Version: 13
- Shipping Plugin: Smart Shipping Calculation

Please let me know if any additional information is required.

**Comment by webhasan** [comment]
If you see duplicate add_to_cart events or any other duplicate event, first make sure you don't have any apps like "Google & YouTube" that could be responsible for those events.

In almost all cases, I have found that when there is a duplicate event, one of the events is coming from the "Google & YouTube" app.

So, before discussing further, can you add an [event prefix](https://youtu.be/98w-kEKLICQ?t=1221) and test it?
