### ISSUE TITLE
No GTM code on the checkout page

### ISSUE THREAD

**Issue by ppc-nb** [webhasan/gtm-datalayer-for-shopify#5]
Hi, I've set everything up according to the instructions.
I created a new pixel with the code from checkout-webpixel.js.
I put my GTM-id in GTM_container_id. But nothing helps, during testing the GTM code is not detected on the checkout page :(.

**Comment by webhasan** [comment]
You need to publish the setup and test it on Debug View to test it. 
You can not test the checkout page with the GTM preview. 

Check the video for further details: https://youtu.be/qNViSdxXq9I

**Comment by webhasan** [comment]
You can not test the checkout page with the GTM preview. 
You need to publish the setup and test it on DebugView or the browser console. 


Check the video for further details: https://youtu.be/qNViSdxXq9I
